---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[1], line 6
      4 import chess.pgn
      5 import chess.svg
----> 6 from cairosvg import svg2png
      7 import subprocess
      8 import os

File ~/miniconda3/envs/CSSLAB/lib/python3.8/site-packages/cairosvg/__init__.py:26
     22 VERSION = __version__ = (ROOT / 'VERSION').read_text().strip()
     25 # VERSION is used in the "url" module imported by "surface"
---> 26 from . import surface  # noqa isort:skip
     29 SURFACES = {
     30     'PDF': surface.PDFSurface,
     31     'PNG': surface.PNGSurface,
   (...)
     34     'SVG': surface.SVGSurface,
     35 }
     38 def svg2svg(bytestring=None, *, file_obj=None, url=None, dpi=96,
     39             parent_width=None, parent_height=None, scale=1, unsafe=False,
     40             background_color=None, negate_colors=False, invert_images=False,
     41             write_to=None, output_width=None, output_height=None):

File ~/miniconda3/envs/CSSLAB/lib/python3.8/site-packages/cairosvg/surface.py:9
      6 import copy
      7 import io
----> 9 import cairocffi as cairo
     11 from .colors import color, negate_color
     12 from .defs import (
     13     apply_filter_after_painting, apply_filter_before_painting, clip_path,
     14     filter_, gradient_or_pattern, linear_gradient, marker, mask, paint_mask,
     15     parse_all_defs, pattern, prepare_filter, radial_gradient, use)

File ~/miniconda3/envs/CSSLAB/lib/python3.8/site-packages/cairocffi/__init__.py:60
     55     error_message = '\n'.join(  # pragma: no cover
     56         str(exception) for exception in exceptions)
     57     raise OSError(error_message)  # pragma: no cover
---> 60 cairo = dlopen(
     61     ffi, ('cairo-2', 'cairo', 'libcairo-2'),
     62     ('libcairo.so.2', 'libcairo.2.dylib', 'libcairo-2.dll'))
     65 class _keepref(object):  # noqa: N801
     66     """Function wrapper that keeps a reference to another object."""

File ~/miniconda3/envs/CSSLAB/lib/python3.8/site-packages/cairocffi/__init__.py:57, in dlopen(ffi, library_names, filenames)
     53         exceptions.append(exception)
     55 error_message = '\n'.join(  # pragma: no cover
     56     str(exception) for exception in exceptions)
---> 57 raise OSError(error_message)

OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': dlopen(libcairo.so.2, 0x0002): tried: 'libcairo.so.2' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibcairo.so.2' (no such file), '/Users/alankritverma/miniconda3/envs/CSSLAB/bin/../lib/libcairo.so.2' (no such file), '/usr/lib/libcairo.so.2' (no such file, not in dyld cache), 'libcairo.so.2' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo.so.2'
cannot load library 'libcairo.2.dylib': dlopen(libcairo.2.dylib, 0x0002): tried: 'libcairo.2.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibcairo.2.dylib' (no such file), '/Users/alankritverma/miniconda3/envs/CSSLAB/bin/../lib/libcairo.2.dylib' (no such file), '/usr/lib/libcairo.2.dylib' (no such file, not in dyld cache), 'libcairo.2.dylib' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo.2.dylib'
cannot load library 'libcairo-2.dll': dlopen(libcairo-2.dll, 0x0002): tried: 'libcairo-2.dll' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibcairo-2.dll' (no such file), '/Users/alankritverma/miniconda3/envs/CSSLAB/bin/../lib/libcairo-2.dll' (no such file), '/usr/lib/libcairo-2.dll' (no such file, not in dyld cache), 'libcairo-2.dll' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo-2.dll'